# -*- coding: utf-8 -*-
"""computer vision project (45,51,55,63,52)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RT9_PDW7TAFvCqtYg1tC45fMst23pXqg
"""

import os
os.environ["CODE_DIR"] = "SAM"

!git clone https://github.com/yuval-alaluf/SAM.git $CODE_DIR
os.chdir(f'./{os.environ["CODE_DIR"]}')

# Ninja build (needed for StyleGAN custom CUDA ops)
!wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
!sudo unzip -o ninja-linux.zip -d /usr/local/bin/
!sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force

!pip install gdown ftfy regex tqdm
!pip install git+https://github.com/openai/CLIP.git

import gdown, os

os.makedirs("pretrained_models", exist_ok=True)
model_path = "pretrained_models/sam_ffhq_aging.pt"

# Assuming the file has been manually uploaded to 'pretrained_models/sam_ffhq_aging.pt'

print("Downloaded:", os.path.exists(model_path))

from google.colab import files
uploaded = files.upload()
input_image_path = list(uploaded.keys())[0]
print("Uploaded:", input_image_path)

from google.colab import files

print("Please upload the 'shape_predictor_68_face_landmarks.dat' file.")
uploaded_predictor = files.upload()

# Verify the uploaded file
shape_predictor_path = "shape_predictor_68_face_landmarks.dat"
if shape_predictor_path in uploaded_predictor:
    print(f"Successfully uploaded: {shape_predictor_path}")
else:
    print(f"Warning: '{shape_predictor_path}' was not found among the uploaded files. Please ensure the filename matches exactly.")

import os
import bz2

print("Current directory:", os.getcwd())

# Download from dlib's official source (compressed)
!wget -q http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
print("bz2 downloaded:", os.path.exists("shape_predictor_68_face_landmarks.dat.bz2"))

# Decompress it
with bz2.BZ2File("shape_predictor_68_face_landmarks.dat.bz2") as f_in:
    data = f_in.read()
with open("shape_predictor_68_face_landmarks.dat", "wb") as f_out:
    f_out.write(data)

# Verify
size = os.path.getsize("shape_predictor_68_face_landmarks.dat")
print(f"Extracted, size: {size} bytes")  # should be ~99,693,937 bytes

import dlib

shape_predictor_path = "shape_predictor_68_face_landmarks.dat"

from scripts.align_all_parallel import align_face

def run_alignment(image_path):
    predictor = dlib.shape_predictor(shape_predictor_path)
    aligned_image = align_face(filepath=image_path, predictor=predictor)
    print("Aligned image has shape:", aligned_image.size)
    return aligned_image

aligned_image = run_alignment(input_image_path)
aligned_image.resize((256, 256))

!wget -q https://github.com/italojs/facial-landmarks-recognition/raw/master/shape_predictor_68_face_landmarks.dat -O shape_predictor_68_face_landmarks.dat
print(os.path.getsize("shape_predictor_68_face_landmarks.dat"))

import torch
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)
!nvidia-smi

import torch
print("CUDA available:", torch.cuda.is_available())
!nvidia-smi

import os
print("cwd:", os.getcwd())
print("pretrained_models exists:", os.path.exists("pretrained_models"))
if os.path.exists("pretrained_models"):
    print("contents:", os.listdir("pretrained_models"))

import os

# Go back to a known root
os.chdir("/content")
print("Reset to:", os.getcwd())

# See what's actually there
for root, dirs, files in os.walk("/content/SAM"):
    # skip going too deep into unrelated folders like .git
    if ".git" in root:
        continue
    depth = root.count(os.sep)
    if depth <= 4:
        print(root)

import os, shutil

os.chdir("/content")
if os.path.exists("SAM"):
    shutil.rmtree("SAM")
print("Cleaned. Now in:", os.getcwd())

os.environ["CODE_DIR"] = "SAM"
!git clone https://github.com/yuval-alaluf/SAM.git $CODE_DIR
os.chdir(f'./{os.environ["CODE_DIR"]}')
print("Now in:", os.getcwd())  # should print /content/SAM, not /content/SAM/SAM

!wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
!sudo unzip -o ninja-linux.zip -d /usr/local/bin/
!sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force

!pip install -q gdown ftfy regex tqdm
!pip install -q git+https://github.com/openai/CLIP.git

import os

os.makedirs("pretrained_models", exist_ok=True)
model_path = "pretrained_models/sam_ffhq_aging.pt"

!wget -q --show-progress "https://huggingface.co/thang101020/aging/resolve/main/sam_ffhq_aging.pt" -O {model_path}

print("Downloaded:", os.path.exists(model_path))
if os.path.exists(model_path):
    print("Size:", os.path.getsize(model_path))  # expect ~2,270,000,000 bytes

import torch
import sys
sys.path.append(".")
sys.path.append("..")

from models.psp import pSp
from argparse import Namespace

ckpt = torch.load(model_path, map_location='cpu')
opts = ckpt['opts']
opts['checkpoint_path'] = model_path
opts = Namespace(**opts)

net = pSp(opts)
net.eval()
net.cuda()
print("Model loaded successfully")

try:
    print("aligned_image exists, size:", aligned_image.size)
except NameError:
    print("aligned_image is missing — need to redo alignment")

import os
print("shape predictor still on disk:", os.path.exists("shape_predictor_68_face_landmarks.dat"))
print("input_image_path:", input_image_path if 'input_image_path' in dir() else "MISSING")

import numpy as np
import torch
import torchvision.transforms as transforms
from PIL import Image
import matplotlib.pyplot as plt

img_transforms = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor(),
    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])
])

input_image = aligned_image.convert("RGB")
transformed_image = img_transforms(input_image)

def run_on_batch(inputs, net):
    with torch.no_grad():
        result_batch = net(inputs.to("cuda").float(), randomize_noise=False, resize=False)
    return result_batch

target_ages = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

results = []
for age in target_ages:
    age_transformer_input = transformed_image.clone()
    age_channel = torch.full((1, 256, 256), age / 100.0)
    input_with_age = torch.cat([age_transformer_input, age_channel], dim=0)
    result = run_on_batch(input_with_age.unsqueeze(0), net)
    result_image = result[0].cpu().detach()
    result_image = ((result_image + 1) / 2).clamp(0, 1)
    results.append(transforms.ToPILImage()(result_image))
    print(f"Generated age {age}")

fig, axes = plt.subplots(1, len(target_ages), figsize=(4*len(target_ages), 4))
for ax, img, age in zip(axes, results, target_ages):
    ax.imshow(img)
    ax.set_title(f"Age {age}")
    ax.axis("off")
plt.tight_layout()
plt.show()